Use server-side apply to configure and trigger backups
This allows us to rely on the Kubernetes API to detect specification
conflicts between this tool and others.

Issue: [sc-15161]

diff --git a/testing/kuttl/e2e/backup/11--backup-with-new-flag.yaml b/testing/kuttl/e2e/backup/11--backup-with-new-flag.yaml
--- a/testing/kuttl/e2e/backup/11--backup-with-new-flag.yaml
+++ b/testing/kuttl/e2e/backup/11--backup-with-new-flag.yaml
@@ -2,12 +2,20 @@ apiVersion: kuttl.dev/v1beta1
 kind: TestStep
 commands:
 - script: |
-    RESULT=$(kubectl-pgo --namespace "${NAMESPACE}" backup backup-cluster --repoName repo1 --options="--type=full --start-fast=y")
+    RESULT=$(kubectl-pgo --namespace "${NAMESPACE}" backup backup-cluster --repoName repo1 --options="--type=full" 2>&1)
+    STATUS=$?
 
     echo "RESULT from taking backup: ${RESULT}"
 
-    if [[ -n $RESULT && "$RESULT" == *"postgresclusters/backup-cluster backup initiated"* ]]; then
-        exit 0
+    if [ "${STATUS-0}" -eq 0 ]; then
+      printf 'Expected error, got none'
+      exit 1
     fi
 
-    exit 1
+    # FIXME(cbandy): why does the output start with a blank line?
+    ERROR=$(echo "${RESULT}" | head -n2)
+
+    if [[ "${ERROR,,}" != *conflict* || "${ERROR}" != *repoName* ]]; then
+      printf 'Expected conflict on repoName, got %q' "${ERROR}"
+      exit 1
+    fi
