Updated KUTTL E2Es for POSIX standard shells
Overall reference
- https://www.gnu.org/software/bash/manual/html_node/Major-Differences-From-The-Bourne-Shell.html

Some specific items include:

Double equals ('==') not supported by all POSIX shells.
- https://www.shellcheck.net/wiki/SC3014

printf %q not supported by all POSIX shells.
- https://ss64.com/bash/printf.html
- https://www.shellcheck.net/wiki/SC3050

arithmetic for loops are undefined
- https://www.shellcheck.net/wiki/SC3005

regex matching (=~) is undefined
- https://www.shellcheck.net/wiki/SC3015

cannot match globs in [..]
- https://www.shellcheck.net/wiki/SC2081

cannot use logical operators in [..]
- https://www.shellcheck.net/wiki/SC2107

Issue: PGO-716

diff --git a/testing/kuttl/e2e/create/01--check_version_validation.yaml b/testing/kuttl/e2e/create/01--check_version_validation.yaml
--- a/testing/kuttl/e2e/create/01--check_version_validation.yaml
+++ b/testing/kuttl/e2e/create/01--check_version_validation.yaml
@@ -4,43 +4,69 @@ kind: TestStep
 commands:
   - script: |
      # Verify the error when the Postgres version given is too low.
+     # Note: case is used here and below as it allows for the use of a
+     # wildcard (*) and is POSIX compliant
      TOO_LOW=$(kubectl-pgo create postgrescluster --pg-major-version=1 toolow 2>&1)
-     if [[ "${TOO_LOW}" != "Error:"*"Invalid value"* ]]; then
-      printf 'Expected invalid value error, got %q\n' "${TOO_LOW}"
-      exit 1
-     fi
+     case "${TOO_LOW}" in
+     "Error:"*"Invalid value"*)
+         ;;
+     *)
+         printf 'Expected invalid value error, got %s\n' "${TOO_LOW}"
+         exit 1
+         ;;
+     esac
 
      # Verify the error when the Postgres version given is too high.
      TOO_HIGH=$(kubectl-pgo create postgrescluster --pg-major-version=100 toohigh 2>&1)
-     if [[ "${TOO_HIGH}" != "Error:"*"Invalid value"* ]]; then
-      printf 'Expected invalid value error, got %q\n' "${TOO_HIGH}"
-      exit 1
-     fi
+     case "${TOO_HIGH}" in
+     "Error:"*"Invalid value"*)
+         ;;
+     *)
+         printf 'Expected invalid value error, got %s\n' "${TOO_HIGH}"
+         exit 1
+         ;;
+     esac
 
      # Verify the error when the Postgres version is not an integer.
      NOT_INT=$(kubectl-pgo create postgrescluster --pg-major-version=14.1 notint 2>&1)
-     if [[ "${NOT_INT}" != "Error: invalid argument"* ]]; then
-      printf 'Expected invalid argument error, got %q\n' "${NOT_INT}"
-      exit 1
-     fi
+     case "${NOT_INT}" in
+     "Error: invalid argument"*)
+         ;;
+     *)
+         printf 'Expected invalid value error, got %s\n' "${NOT_INT}"
+         exit 1
+         ;;
+     esac
 
      # Verify the error when the Postgres version is not a number.
      NOT_NUM=$(kubectl-pgo create postgrescluster --pg-major-version=x notnum 2>&1)
-     if [[ "${NOT_NUM}" != "Error: invalid argument"* ]]; then
-      printf 'Expected invalid argument error, got %q\n' "${NOT_NUM}"
-      exit 1
-     fi
+     case "${NOT_NUM}" in
+     "Error: invalid argument"*)
+         ;;
+     *)
+         printf 'Expected invalid value error, got %s\n' "${NOT_NUM}"
+         exit 1
+         ;;
+     esac
 
      # Verify the error when the Postgres version flag is not provided.
      MISSING=$(kubectl-pgo create postgrescluster missing 2>&1)
-     if [[ "${MISSING}" != "Error: required flag"* ]]; then
-      printf 'Expected required flag error, got %q\n' "${MISSING}"
-      exit 1
-     fi
+     case "${MISSING}" in
+     "Error: required flag"*)
+         ;;
+     *)
+         printf 'Expected required flag error, got %s\n' "${MISSING}"
+         exit 1
+         ;;
+     esac
 
      # Verify the error when the Postgres version value is empty.
      NOT_SET=$(kubectl-pgo create postgrescluster --pg-major-version=  notset 2>&1)
-     if [[ "${NOT_SET}" != "Error: invalid argument"* ]]; then
-      printf 'Expected invalid argument error, got %q\n' "${NOT_SET}"
-      exit 1
-     fi
+     case "${NOT_SET}" in
+     "Error: invalid argument"*)
+         ;;
+     *)
+         printf 'Expected invalid argument error, got %s\n' "${NOT_SET}"
+         exit 1
+         ;;
+     esac
