Update Kuttl tests to better handle variable error output

diff --git a/testing/kuttl/e2e/restore/01--validation.yaml b/testing/kuttl/e2e/restore/01--validation.yaml
--- a/testing/kuttl/e2e/restore/01--validation.yaml
+++ b/testing/kuttl/e2e/restore/01--validation.yaml
@@ -14,7 +14,7 @@ commands:
       exit 1
     }
 
-    [[ "${RESULT}" == 'Error:'*'repoName: Required value' ]] || {
+    [[ "${RESULT}" == *'Error:'*'repoName: Required value' ]] || {
       echo "Expected an error message, got:"
       echo "${RESULT}"
       exit 1
