Updated KUTTL E2Es for POSIX standard shells
Overall reference
- https://www.gnu.org/software/bash/manual/html_node/Major-Differences-From-The-Bourne-Shell.html

Some specific items include:

Double equals ('==') not supported by all POSIX shells.
- https://www.shellcheck.net/wiki/SC3014

printf %q not supported by all POSIX shells.
- https://ss64.com/bash/printf.html
- https://www.shellcheck.net/wiki/SC3050

arithmetic for loops are undefined
- https://www.shellcheck.net/wiki/SC3005

regex matching (=~) is undefined
- https://www.shellcheck.net/wiki/SC3015

cannot match globs in [..]
- https://www.shellcheck.net/wiki/SC2081

cannot use logical operators in [..]
- https://www.shellcheck.net/wiki/SC2107

Issue: PGO-716

diff --git a/testing/kuttl/e2e/restore/01--validation.yaml b/testing/kuttl/e2e/restore/01--validation.yaml
--- a/testing/kuttl/e2e/restore/01--validation.yaml
+++ b/testing/kuttl/e2e/restore/01--validation.yaml
@@ -8,24 +8,28 @@ commands:
     RESULT=$( 2>&1 kubectl-pgo --namespace "${NAMESPACE}" restore restore-cluster )
     STATUS=$?
 
-    [[ "${STATUS}" -ne 0 ]] || {
+    [ "${STATUS}" -ne 0 ] || {
       echo "Expected failure, got ${STATUS}"
       echo "STDOUT+STDERR: ${RESULT}"
       exit 1
     }
 
-    [[ "${RESULT}" == *'Error:'*'repoName: Required value' ]] || {
-      echo "Expected an error message, got:"
-      echo "${RESULT}"
-      exit 1
-    }
+    case "${RESULT}" in
+    *'Error:'*'repoName: Required value')
+        ;;
+    *)
+        echo "Expected an error message, got:"
+        echo "${RESULT}"
+        exit 1
+        ;;
+    esac
 
     RESTORE=$(
       kubectl --namespace "${NAMESPACE}" get postgrescluster/restore-cluster \
         --output 'jsonpath-as-json={.spec.backups.pgbackrest.restore}'
     )
 
-    [[ "${RESTORE}" == '[]' ]] || {
+    [ "${RESTORE}" = '[]' ] || {
       echo "Expected restore section to be empty, got ${RESTORE}"
       exit 1
     }
diff --git a/testing/kuttl/e2e/restore/30--conflict.yaml b/testing/kuttl/e2e/restore/30--conflict.yaml
--- a/testing/kuttl/e2e/restore/30--conflict.yaml
+++ b/testing/kuttl/e2e/restore/30--conflict.yaml
@@ -25,22 +25,23 @@ commands:
     )
     STATUS=$?
 
-    [[ "${STATUS}" -ne 0 ]] || {
+    [ "${STATUS}" -ne 0 ] || {
       echo "Expected failure, got ${STATUS}"
       echo "STDOUT+STDERR: ${RESULT}"
       echo "Managed Fields: ${BEFORE}"
       exit 1
     }
 
-    [[
-        "${RESULT}" == *'Error: Apply failed'*'2 conflicts'* &&
-        "${RESULT}" == *'.metadata.annotations.'*'/pgbackrest-restore'* &&
-        "${RESULT}" == *'.spec.backups.pgbackrest.restore.enabled'
-    ]] || {
-      echo "Expected an error message, got:"
-      echo "${RESULT}"
-      exit 1
-    }
+    case "${RESULT}" in
+    *'Error: Apply failed'*'2 conflicts'*'.metadata.annotations.'*'/pgbackrest-restore'*'.spec.backups.pgbackrest.restore.enabled')
+        ;;
+    *)
+        echo "Expected an error message, got:"
+        echo "${RESULT}"
+        exit 1
+        ;;
+    esac
+
 
     # Remove the annotation.
     kubectl --namespace "${NAMESPACE}" annotate postgrescluster/restore-cluster \
